// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

float u2f(uint x);

uint hash(uint x);
uint hash(uint2 x);

float gradient(int x);
float2 gradient(int2 x);

float gradient_noise_2D(float2 p);

float fade_hermite(float t);
float2 fade_hermite_2D(float2 p);

float bilerp(float a, float b, float c, float d, float x, float y);
// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
float _Period;
float2 _Offset;
RWTexture2D<float4> Result;

[numthreads(1,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    // TODO: insert actual code here
    
    float value = gradient_noise_2D((float2(id.xy) + _Offset) / _Period);
    value = (value + 1) /2; // revert domain to [0,1) so it can fit in color value
    float2 a = gradient(int2(id.xy));
    Result[id.xy] = float4(value, value, value, 1.0);
    
}

float gradient_noise_2D(float2 p)
{
    int2 i = int2(floor(p));
    float2 g0 = u2f(hash(i));
    float2 g1 = u2f(hash(i + int2(1, 0)));
    float2 g2 = u2f(hash(i + int2(0, 1)));
    float2 g3 = u2f(hash(i + int2(1, 1)));

    float2 f = frac(p);

    float2 a = fade_hermite_2D(f);
    return bilerp(g0, g1, g2, g3, a.x, a.y);
}

float bilerp(float a, float b, float c, float d, float x, float y)
{
    return lerp(lerp(a, b, x), lerp(c, d, x), y);
}
float fade_hermite(float t) {  return (3.0 - 2.0*t)*t*t;}
float2 fade_hermite_2D(float2 p)
{
    return float2(fade_hermite(p.x), fade_hermite(p.y));
}

float gradient(int x)
{
    return u2f(hash(uint(x))) * 2.0 - 1.0;
}
static const float TAU = 6.283185307179586;
float2 gradient(int2 x)
{
    float angle = u2f(hash(uint2(x))) * TAU;
    return float2(cos(angle), sin(angle));
}
uint hash(uint x)
{
    x = (x ^ (x >> 16)) * 0x21f0aaadU;
    x = (x ^ (x >> 15)) * 0x735a2d97U;
    
    return x ^ (x >> 15);
}
uint hash(uint2 x) { return hash(x.x ^ hash(x.y)); }  // for 2D input
float u2f(uint x) { return float(x >> 8U) * asfloat(0x33800000U); }


