// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

float u2f(uint x);
uint hash(uint x);
float h(float x);
float value_noise_1D_quintic(float p);
float fade_quintic(float t);
// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
float _Period;
RWTexture2D<float4> Result;

[numthreads(256,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    // TODO: insert actual code here
    
    float value = value_noise_1D_quintic(float(id.x) / _Period);
     value = (value + 1) /2; // revert domain to [0,1) so it can fit in color value
    Result[id.xy] = float4(value, value, value, 1.0);
     
    
}

float value_noise_1D_quintic(float p)
{
    int i = floor(p);
    float f = frac(p);
    float a = fade_quintic(f);
    return lerp(h(i), h(i + 1), a);
}

float h(float x)
{
    return u2f(hash(x)) * 2.0 - 1.0;
    // change domain from [0,1) to [-1, 1)
}

uint hash(uint x)
{
    x = (x ^ (x >> 16)) * 0x21f0aaadU;
    x = (x ^ (x >> 15)) * 0x735a2d97U;
    
    return x ^ (x >> 15);
}
float fade_quintic(float t) { return ((6.0*t-15.0)*t+10.0)*t*t*t; }
float u2f(uint x) { return float(x >> 8U) * asfloat(0x33800000U); }


