// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

float u2f(uint x);
uint hash(uint x);
uint hash(uint2 x);
// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> Result;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    // TODO: insert actual code here
    
    float value = u2f(hash(id.xy));
    Result[id.xy] = float4(value, value, value, 1.0);
     
    
}

uint hash(uint x)
{
    x = (x ^ (x >> 16)) * 0x21f0aaadU;
    x = (x ^ (x >> 15)) * 0x735a2d97U;
    
    return x ^ (x >> 15);
}
uint hash(uint2 x) { return hash(x.x ^ hash(x.y)); }  // for 2D input
float u2f(uint x) { return float(x >> 8U) * asfloat(0x33800000U); }


