// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

float u2f(uint x);

uint hash(uint x);
uint hash(uint2 x);

float gradient(int x);
float2 gradient(int2 x);

float3 gradient_noise_2D(float2 p);

float fade_quintic(float t);
float2 fade_quintic_2D(float2 p);

float bilerp(float a, float b, float c, float d, float x, float y);

float fbm2e(float2 p, int octaves);
float geometricSum(float G, float n);
// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
float _Period;
float _Lacunarity;
float _Gain;
int _Octaves;

float2 _Offset;
RWTexture2D<float4> Result;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    // TODO: insert actual code here
    
    float val = fbm2e((float2(id.xy) + _Offset) / _Period, _Octaves);
    float m = geometricSum(_Gain, _Octaves);
    val += m; val /= 2 * m;
    Result[id.xy] = float4(val, val, val, 1.0);
    
    
}
float fbm2e(float2 p, int octaves)
{
    float sum = 0.0f;
    float amp = 1.0, freq = 1.0;
    float2 d = float2(0,0);
    float max = 0.0f;
    for (int i = 0; i < octaves; i++)
    {
        float3 noise = gradient_noise_2D(p * freq);
        
        d += noise.xy;
        float w = 1.0 / (1.0 + dot(d,d)); // gradient/slope based wieght??
        // what's the max value of d?
        // max of w = 1 / ( 1 + d^2) assume 1. so max of w = 1/2
        sum += amp * noise.z * w; //max added = 1 * 1 * 1/2 or += 1/2
        //infinite sum  of 1/2 + 1/4 + 1/8 ... = 1 
        
        freq *= _Lacunarity;
        amp *= _Gain;
    }
    return sum;
}

float3 gradient_noise_2D(float2 p)
{
    int2 i = int2(floor(p));
    float2 g0 = gradient(i);
    float2 g1 = gradient(i + int2(1, 0));
    float2 g2 = gradient(i + int2(0, 1));
    float2 g3 = gradient(i + int2(1, 1));

    float2 f = frac(p);
    float v0 = dot(g0, f);
    float v1 = dot(g1, f - float2(1.0, 0.0));
    float v2 = dot(g2, f - float2(0.0, 1.0));
    float v3 = dot(g3, f - float2(1.0, 1.0));

    float2 a = fade_quintic_2D(f);
    
    float v = bilerp(v0, v1, v2, v3, a.x, a.y);

    float2 g = bilerp(g0, g1, g2, g3, a.x, a.y);
    float2 d = lerp(float2(v1,v2)-v0, v3-float2(v2,v1), a.yx); // derivatives of bmix with respect to the interpolant
    float2 da = ((f-2.0)*f+1.0)*30.0*f*f;

    return float3(g + d*da, v);
}

float bilerp(float a, float b, float c, float d, float x, float y)
{
    return lerp(lerp(a, b, x), lerp(c, d, x), y);
}
float fade_quintic(float t) { return ((6.0*t-15.0)*t+10.0)*t*t*t; }
float2 fade_quintic_2D(float2 p)
{
    return float2(fade_quintic(p.x), fade_quintic(p.y));
}

float gradient(int x)
{
    return u2f(hash(uint(x))) * 2.0 - 1.0;
}
static const float TAU = 6.283185307179586;
float2 gradient(int2 x)
{
    float angle = u2f(hash(uint2(x))) * TAU;
    return float2(cos(angle), sin(angle));
}
uint hash(uint x)
{
    x = (x ^ (x >> 16)) * 0x21f0aaadU;
    x = (x ^ (x >> 15)) * 0x735a2d97U;
    
    return x ^ (x >> 15);
}
uint hash(uint2 x) { return hash(x.x ^ hash(x.y)); }  // for 2D input
float u2f(uint x) { return float(x >> 8U) * asfloat(0x33800000U); }

float geometricSum(float G, float n) { return ((G * (pow(G, n + 1) - 1)) / (G -1)) + 0.5; }